spring.application.name=Visitas
server.port:4569

# Database
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.url=jdbc:postgresql://db.kjrilwnhiaqlaibikmjr.supabase.co:5432/postgres
#spring.datasource.url=jdbc:postgresql://localhost:5432/cv_client
#spring.datasource.username=postgres
#spring.datasource.password=postgres
#spring.datasource.password=Habana**.537

spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always

#JWT
# En producci�n esto va en variables de entorno, NUNCA hardcodeado
jwt.secret=${JWT_SECRET}
# Expiraci�n del Access Token: 15 minutos en milisegundos
jwt.expiration=900000
# Expiraci�n del Refresh Token: 7 d�as en milisegundos
jwt.time.refresh-expiration=604800000

#EMAIL (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pedritos881@gmail.com
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.base-url=http://localhost:4569

